using System;
using Obvious.Soap;
using Sirenix.OdinInspector;
using UnityEngine;

namespace Conjure.GameInitialization
{
    public class InitilizeManager : SerializedMonoBehaviour
    {
        [SerializeField] private GameObject toKeepLoaded;
        [Required]
        [SerializeField] private ScriptableEventNoParam gameInitializedEvent;

        private void Start()
        {
            if(toKeepLoaded is not null)
            {
                DontDestroyOnLoad(toKeepLoaded);
            }
            
            // INITIALIZE THE REST
        
            gameInitializedEvent.Raise();
        }
        
    }
}