using System;
using System.Collections;
using System.Collections.Generic;
using Conjure.Input;
using Obvious.Soap;
using Sirenix.OdinInspector;
using UnityEngine;
using UnityEngine.InputSystem;

public class InputManager : SerializedMonoBehaviour
{
    [SerializeField] private PlayerEnum player = PlayerEnum.Player1;
    [SerializeField] private Vector3Variable[] vectorVariables = new Vector3Variable[2];
    
    [ReadOnly]
    [BoxGroup("Debug")]

    public void OnMove(InputAction.CallbackContext context)
    {
        int id = context.control.device.deviceId;
        
        Vector2 direction = context.action.ReadValue<Vector2>();
        vectorVariables[(int)player].Value = new Vector3(direction.x, 0, direction.y);
    }
}
